// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';

const SUPABASE_URL = "https://bdfdxsbwofalflaiqozi.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJkZmR4c2J3b2ZhbGZsYWlxb3ppIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTg1MjY2NTEsImV4cCI6MjA3NDEwMjY1MX0.CC-6VIQnnbzDR_6t_OvOv0d42gQSveyTkNgfkB7ngo4";

// Service Role Key for admin operations
// IMPORTANT: Replace this with your actual service role key from Supabase Dashboard
const SUPABASE_SERVICE_ROLE_KEY = import.meta.env.VITE_SUPABASE_SERVICE_ROLE_KEY || "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJkZmR4c2J3b2ZhbGZsYWlxb3ppIiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImlhdCI6MTc1ODUyNjY1MSwiZXhwIjoyMDc0MTAyNjUxfQ.YOUR_SERVICE_ROLE_KEY_HERE";

// Regular client for user operations
export const supabase = createClient(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});

// Admin client for admin operations (createUser, deleteUser, etc.)
export const supabaseAdmin = createClient(SUPABASE_URL, SUPABASE_SERVICE_ROLE_KEY, {
  auth: {
    autoRefreshToken: false,
    persistSession: false
  }
});